from django.contrib.gis.geos.geometry import GEOSGeometry as GEOSGeometry
from typing import Any, Iterable, Optional, Tuple, Union

class Point(GEOSGeometry):
    has_cs: bool = ...
    def __init__(
        self, x: Union[Tuple[float, ...], float, None] = ..., y: Optional[float] = ..., z: Optional[float] = ..., srid: Optional[int] = ...
    ) -> None: ...
    def __iter__(self) -> Iterable[float]: ...
    def __len__(self) -> int: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, value: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, value: float) -> None: ...
    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, value: float) -> None: ...
    @property
    def tuple(self) -> Tuple[int, ...]: ...
    @tuple.setter
    def tuple(self, tup: Tuple[int, ...]) -> None: ...
    coords = tuple
